### ISSUE TITLE
提个视觉冲击的建议

### ISSUE THREAD

**Issue by lete114** [jaycethanks/coralize#1]
让用户可以指定区域背景颜色替换，而不是上来就直接是一大块颜色，而且这些颜色冲击力太强，无法专心写代码

- 可自定义顶部栏背景颜色
- 可自定义侧边栏背景颜色
- 可自定义顶部栏背景颜色

虽然可以改工作目录的配置(.vscode/settings.json)来实现，但这太难受了

![image](https://user-images.githubusercontent.com/48512251/236617709-b261bea2-795a-453a-a1f0-8cb2e75077ef.png)

**Comment by joisun** [comment]
这个配置加上了， 升级版本就好了
